language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - python setup.py sdist --formats=gztar -k
  - find ./dist -iname "*.tar.gz" -print0 | xargs -0 pip install
  - pip install coveralls
script:
  - coverage run --source=namedparser --omit='namedparser/testsuite/*' setup.py test
after_success:
  - coveralls
